version: '3.7'

services:
  elixir_database:
    image: postgres:12.2-alpine
    container_name: elixir_database
    ports:
      - 5432:5432
    volumes:
      - elixir_pg_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  elixir_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: elixir_app
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - elixir_database
    tty: true

volumes:
  elixir_pg_database:
    external: true
